name: ðŸ¥¯ Release Bun

on:
  release:
    types: [published]

permissions:
  contents: write
  packages: write

jobs:
  bitzy:
    name: ðŸ¥¯ Bitzy on Buns
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ§¾ Checkout source
        uses: actions/checkout@v3

      - name: ðŸ·ï¸ Set release version
        id: setver
        run: |
          VERSION="${GITHUB_REF#refs/tags/v}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: ðŸ¥¯ Run Bitzy on Buns
        uses: Chocobitey/buns@v1.0.1
        with:
          name: ${{ vars.NAME }}
          version: ${{ steps.setver.outputs.version }}
